### ISSUE TITLE
Export the pretty stuff

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#266]
Basically, the `{riskassessment}` package could serve as a hub to extract all the sexy graphics we've developed into the app. That is, they can produce any cards & graphics programmatically for their own purposes, whatever they may be. Namely, I'm thinking of the community usage plot and also the any of the cards from any tab.

**Comment by ScottSchumacker** [comment]
Hi @AARON-CLARK, Thank you! Yes, I spent some time learning about roxygen2 and roxygen comments and the different tags. It has been a while since I have worked on R packages but things are definitely more clear now. I have created a new branch "ss-266", created off of the dev branch that I will be working on for this issue.

**Comment by AARON-CLARK** [comment]
closed with #377
