### ISSUE TITLE
Should we change our GitHub repo to `pharmaR/riskassessment`

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#304]
The naming of our repo is not consistent with the package name (`{riskassessment} without a blank space) and thus, doesn't follow the precedent set by R package developers around the world. What are the ramifications?

Cons
* A ton of old links would break
* developers would need to potentially re-clone the data?

Pros
* Less confusing when naming is consistent
* Our app isn't even listed on the [riskmetric](https://pharmar.github.io/riskmetric/index.html) README or doc site yet, so maybe its the perfect time to change our repo name.

**Comment by Xyarz** [comment]
I like the suggestion in order to enhance consistency and I feel like neither the link breaking shouldn't be that much of an issue, nor should be the re-cloning. The only point to think about would be, that both the tab as well as title etc. are named Risk Assessment - so I am not sure what would be more coherent here.

**Comment by AARON-CLARK** [comment]
Done on 1/6/2023
