### ISSUE TITLE
Expand User Roles

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/riskassessment#346]
We need user roles going beyond `admin` versus `nonadmin` 

Maybe ditch `nonadmin` in favor of other roles, like `reviewer`, `user`, `approver`, ???
What privileges would each role assume?

**Comment by AARON-CLARK** [comment]
Thanks @Robert-Krajcik, I agree - it's time we consider creating some roles besides `admin` and `nonadmin`. I could see an organization wanting these roles, for example:


`admin` - all privileges
`lead` - all privileges of an admin, minus the ability to manage userids/passwords. So basically, they still have full access to the assessment re-weighting tab. I like the name `lead` over "approver" only because their job may include rejecting pkgs too. So in that way, they do more than approving.
`reviewer` - all privileges of a lead, except ...

* can't make any final package decisions
* can't revert package decisions
* can't delete packages from db (feature coming soon. See #340 )
* no access to anything from administrative tools tab

Also, I'm open to better naming options for these roles.

**Comment by AARON-CLARK** [comment]
With the recent addition of #487, perhaps certain roles or users have access to review certain classes of packages. For example, perhaps I want to create a role that can be a `reviewer` on any package but has `lead` type privilege for "TLG" class packages!

**Comment by AARON-CLARK** [comment]
closed via #527
