### ISSUE TITLE
package version discrepancy on upload

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/riskassessment#385]
Deleting package rvest.  Note version.
![image](https://user-images.githubusercontent.com/75215958/216400652-f13e5274-c4be-48a9-9910-9000b6dc09d2.png)
And then upload the package again:
![image](https://user-images.githubusercontent.com/75215958/216400719-a751bc6c-c549-4109-8e87-a951dd110bdf.png)
Note the version is one level back from the one just deleted.
Go to the sidebar and select the package, and the correct version is shown:
![image](https://user-images.githubusercontent.com/75215958/216400930-019b702c-9eb7-4b4a-9074-8f51ff5f001d.png)

**Comment by borgmaan** [comment]
This is due to a bug in the way that `riskassessment` is handling versions and interfacing with `riskmetric`. I discovered this today when looking at #410.

Currently, `riskassessment` [inserts the latest CRAN version](https://github.com/pharmaR/riskassessment/blob/dev/R/utils_insert_db.R#L60-L66) as the package version in the DB. 

However, it [uses](https://github.com/pharmaR/riskassessment/blob/1cfb13e34ad4649fda1b63517792b8cd5b804ba3/R/mod_uploadPackage.R#L286) the version derived from a call to `riskmetric::pkg_ref` to populate the version shown in that summary table. 

Given the way `riskmetric::pkg_ref` works, this will default to a `pkg_install` source when the package is installed locally (as `rvest` is in our case with v1.0.2 being in our `renv.lock` file). You will see 1.0.2 show up in the summary table as that matches what is in your local library. However, it will be inserted to the DB as 1.0.3 and will show up as that version in subsequent activity. 

In addition to the bug you show here, this also leads to a severe bug related to storing `riskmetric` metrics and scores within the DB. `insert_riskmetric_to_db` also uses a ["bare" call to `pkg_ref`](https://github.com/pharmaR/riskassessment/blob/ef695c5942b72754e5b6f74107e3196d169bf77c/R/utils_insert_db.R#L147). In this case, **the metrics being written back to the DB can be for a different version of the package than what is logged in the `package` table in the database.** This is not the desired behavior. 

`shiny` is another good example where the repo's lockfile version is older than latest CRAN and `riskassessment` will log the latest CRAN version in the DB when inserting into the `packages` table but will insert metrics for the older, locally installed, version when populating the `package_metrics` table.

**Comment by AARON-CLARK** [comment]
closed with patch in #413. Will revisit a more comprehensive solution with #410 solution.
