### ISSUE TITLE
Individual tests with shinytest2 are failing

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/riskassessment#431]
Even after locally installing `riskassessment` from build::install()
and specifying `library(shinytest2)`
individual tests are failing (tests that don't use shinytest2 all pass)
`Error in `eval(code, test_env)`: object 'AppDriver' not found`

and devtools::test() shinytest2 tests all fail for the same reason.

in https://devtools.r-lib.org/reference/test.html
"test() runs all tests in a package. It's a shortcut for [testthat::test_dir()](https://testthat.r-lib.org/reference/test_dir.html)"
Curiously, testthat::test_dir(".") **mostly** works
Still got a timeout error for `test-uploadPackage.R:115:3`

Specifying
`  app <- shinytest2::AppDriver$new(app_dir = test_path("test-apps"), load_timeout = 30*1000)`
allows the individual tests to pass.
I know that testthat.R is not used for individual tests, but it also seems to get ignored
when running `devtools::test()`

**Comment by imran3004** [comment]
I am able to reproduce the bug. Looking into it.

**Comment by imran3004** [comment]
From similar posts online, it seems that this may be due to loading of many packages. 

Ref: https://github.com/rstudio/shinytest/issues/111#issuecomment-310101951

@Robert-Krajcik , the solution you proposed works. 

`app <- shinytest2::AppDriver$new(app_dir = test_path("test-apps"), load_timeout = 30*1000)`

If we are to use this, we'll need to look through all instances of this call and set the argument. 

Is that okay? Should I go ahead and implement this change?

**Comment by AARON-CLARK** [comment]
On 6/6 dev meetup, we discussed a good resolution would be to keep things AS-IS but compose a wiki that describes a good workflow on how to run the tests that involves installing the local branch and running. More details to come in the wiki. @imran3004

**Comment by aclark02-arcus** [comment]
This issue is stale and no longer an issue.
