### ISSUE TITLE
Allow other pkg versions besides most recent version

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/riskassessment#52]
Fix versioning number
- [ ] The version dropdown should display the version(s) uploaded by the user (not the most recent one of the package).
- [ ] The db should be able to store different versions of the same package. Hence, some tables (like the Packageinfo one) should be modified accordingly (e.g. Packageinfo should have a primary key - package name - and a secondary key - package version). The `update` and `insert` may need to be updated.

**Comment by Robert-Krajcik** [comment]
How can we tell if the version provided in the *.csv file is not mistyped?
Can we assume the version uploaded by the user is the one they have installed?
Or do we need to pull the version history out of CRAN?

**Comment by Robert-Krajcik** [comment]
Overall plan:

- [ ] Given `uploadpackage.R` reads *.csv file into df pkgs_file
- [ ] Verify that the package name exists on CRAN
- [ ] Verify that the version exists and is available using the `versions` package function `available.versions()`
- [ ] If either test fails, issue message and delete the row in pkgs_file and reset the row numbers
- [ ] Otherwise, continue but with the following changes.
- [ ] Multiple versions per package will be allowed, not just the latest one. 
- [ ] Version dropdown in sidebar will display the version(s) uploaded by the user.

**Comment by Robert-Krajcik** [comment]
In dbupload.R, information on the latest version is web-scraped.
```{r, eval=FALSE}
        read_html(paste0(
          "https://cran.r-project.org/web/packages/",
          package_name
        ))
```
However, if the package_version read is not equal to the current version, we can do something else
`if (ver != package_version) signalCondition(e)`
and use the R6Class function `description()` to get information about the package that is currently installed

```{r, eval=FALSE}
          if (file.exists(paste(i, "/", package_name, sep = "")) == TRUE) {
            i <- paste0(i, "/", package_name)
            d <- description$new(i)
            title <- d$get("Title")
            ver <- d$get("Version")
            desc <- d$get("Description")
            desc <- gsub("'", "", desc) # remove single quotes
            main <- d$get("Maintainer")
            auth <- d$get("Author")
            lis <- d$get("License")
            pub <- d$get("Packaged")
```
So it is possible to have more than one version of a package.
![image](https://user-images.githubusercontent.com/62262182/93358402-6a4f4800-f80f-11ea-8502-f60bc46aa37f.png)

![image](https://user-images.githubusercontent.com/62262182/93358526-966ac900-f80f-11ea-9be8-cee54fa36d38.png)

and, at least, the overall package information is different for each version
![image](https://user-images.githubusercontent.com/62262182/93358620-b7331e80-f80f-11ea-833c-1bdc1832831a.png)

![image](https://user-images.githubusercontent.com/62262182/93358699-cca84880-f80f-11ea-8612-684c947ba005.png)

**Comment by Robert-Krajcik** [comment]
I can make all the comments specific to a version,
and since the Community usage metrics runs across versions,
I can show the information **up to** the version selected.
![image](https://user-images.githubusercontent.com/62262182/93625638-4a0abf00-f9b0-11ea-94c7-345832dc014f.png)

![image](https://user-images.githubusercontent.com/62262182/93625716-69a1e780-f9b0-11ea-899e-f5885c666fba.png)

**Comment by Robert-Krajcik** [comment]
Right now the only issue I see is that maintenance metrics (and testing metrics) is derived from 
the riskmetric `pkg_ref()` function which retrieves the version using `utils::packageVersion` if the package is locally installed.
Maybe we can modify the version that gets passed to `pkg_assess()`?

```{r, eval=FALSE}
  package_riskmetric1 <<-
    pkg_ref(package_name) %>%
    as_tibble() %>%
    pkg_assess() %>%
    pkg_score() %>%
    mutate(risk = summarize_scores(.))
```

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Is this still something we are looking to implement? Since we are pulling in remote sources for `{riskmetric}`, for each assessment it only makes sense to use the most recent version. The only time I can personally think of where this might matter is on reassessments, but you wouldn't be able to retroactively score an older version.

**Comment by Jeff-Thompson12** [comment]
Seems plausible but we probably need to start a new brainstorming issue. Implementation would require some form of comparison module. This would also potentially require changes in the database that wouldn't be backward compatible, but that was true with versioning as well.

**Comment by aclark02-arcus** [comment]
closing in favor of #534
