### ISSUE TITLE
Issue with Opening CRAN URL: 'https://cran.rstudio.com/src/contrib/PACKAGES'

### ISSUE THREAD

**Issue by paolanh** [pharmaR/riskassessment#763]
I'm encountering an issue with the riskassessment app where it cannot open the URL to CRAN when trying to upload packages through the R/mod_uploadPackage.R and  R/mod_packegeDependecies.R. The specific error message I receive is:

<img width="338" alt="warning" src="https://github.com/pharmaR/riskassessment/assets/61955690/8238b4c6-9733-45cf-a576-1b838fa42b8c">

R version: 4.2.1

This issue occurs when I attempt to upload a package using the provided UI in the app.

The app fails to open the URL to CRAN, which prevents any further action from completing successfully.

Could someone please help diagnose this issue or provide a workaround? Thank you for your assistance!

**Comment by aclark02-arcus** [comment]
Hi @paolanh! Thanks for opening an issue. Unfortunately, I wasn't able to replicate the issue from the `master` branch. So, I have a couple questions:

* Does the machine running the app have an internet connection?
* Are you getting this message when deployed somewhere (shinyapps.io or posit connect?) or are you running it locally?
* Did you sync your dependencies using `renv::restore()` before launching the app? What happens when you run `renv::status()`?
* Just curious, what happens if you run the following?

    ```r
    options("repos")
    ```

* Does the issue solve itself if you the following before re-launching the app:
    ```r
    options(repos="https://cran.rstudio.com/")
    ```

If that CRAN mirror is truly the issue, the `dev` branch actually has a new feature that allows the app deployer to change the package repo to one of your choice using the `inst/db-config.yml` file as seen [here](https://github.com/pharmaR/riskassessment/blob/dev/inst/db-config.yml#L2). So it could be worth a try testing that out. We do hope to merge our `dev` branch into `master` soon (within the next week or so).

Please report back and let me know how it goes!

**Comment by paolanh** [comment]
Hi @aclark02-arcus,

Thank you for your response, and apologies for my delayed reply; we had paused the implementation of this project. It appears the issue is related to Posit Connect—on a personal computer, the app works well. We'll now collaborate with our IT department to find a solution. Thanks again!
